# Generated by Django 5.2.17 on 2026-09-18 01:10

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

import penni_more.transactions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_account_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("name", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name__regex", "\\S")),
                        name="transactions_category_name_not_blank",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="transactions_category_name_ci_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("income", "Income"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("date", models.DateField(default=penni_more.transactions.models.utc_today)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["account", "date"], name="transactions_account_date_idx"),
                    models.Index(
                        fields=["target_account", "date"], name="transactions_target_date_idx"
                    ),
                    models.Index(
                        fields=["-date", "-created_at", "-id"], name="transactions_list_order_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name__regex", "\\S")),
                        name="transactions_transaction_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="transactions_transaction_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("transaction_type__in", ("expense", "income", "transfer"))
                        ),
                        name="transactions_transaction_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_account__isnull", False), ("transaction_type", "transfer")
                            ),
                            models.Q(
                                models.Q(("transaction_type", "transfer"), _negated=True),
                                ("target_account__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="transactions_transaction_target_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("target_account__isnull", True),
                            models.Q(("account", models.F("target_account")), _negated=True),
                            _connector="OR",
                        ),
                        name="transactions_transaction_accounts_distinct",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Exact(
                            models.Func(
                                models.F("additional_data"),
                                function="jsonb_typeof",
                                output_field=models.CharField(),
                            ),
                            models.Value("object"),
                        ),
                        name="transactions_transaction_additional_data_object",
                    ),
                ],
            },
        ),
    ]
